name: Optimize map and deploy

on:
  push:
    branches:
      - f_ownDeploy

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      - name: Bash
        run: |
          ls -al
          git config --global user.email "karstens@pik-potsdam.de"
          git config --global user.name  "kk330"
          git checkout f_ownDeploy
          git commit -am "Adding files"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BASE_BRANCH: f_ownDeploy

      - name: Bash2
        run: |
          ls -al
